//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clntes
    {
        public string tpos_dcmnto_cdgo { get; set; }
        public string clntes_idntfccion { get; set; }
        public string clntes_rzon_scial { get; set; }
        public string clntes_drccion { get; set; }
        public string clntes_tlfno { get; set; }
        public string clntes_fax { get; set; }
        public string clntes_mail { get; set; }
        public string cddes_cdgo { get; set; }
        public string clntes_cntcto { get; set; }
        public string clntes_tlfno_cntcto { get; set; }
        public string clntes_cllar_cntcto { get; set; }
        public string clntes_mail_cntcto { get; set; }
        public string clntes_actvo { get; set; }
        public string usrios_cdgo { get; set; }
        public Nullable<System.DateTime> fcha_prcso { get; set; }
    }
}
