//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clntes_drccnes
    {
        public int consecutivo { get; set; }
        public string clntes_idntfccion { get; set; }
        public string clntes_drccnes_nmbre { get; set; }
        public string clntes_drccnes_drccion { get; set; }
        public string clntes_drccnes_cntcto { get; set; }
        public string cddes_cdgo { get; set; }
        public string clntes_drccnes_actvo { get; set; }
        public string clntes_drccnes_tlfno { get; set; }
        public string clntes_drccnes_obsrvcnes { get; set; }
        public string usrios_cdgo { get; set; }
        public Nullable<System.DateTime> fcha_prcso { get; set; }
    }
}
