//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cntros
    {
        public string tpos_dcmnto_cdgo { get; set; }
        public string cntros_cdgo { get; set; }
        public string cntros_rzon_scial { get; set; }
        public string cddes_cdgo { get; set; }
        public string cntros_scrsal { get; set; }
        public string cntros_drccion { get; set; }
        public string cntros_tlfno { get; set; }
        public string cntros_mail { get; set; }
        public string cntros_actvo { get; set; }
    }
}
