//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_vles_srvcios
    {
        public int consecutivo { get; set; }
        public Nullable<int> enc_vles_nmro { get; set; }
        public string srvcios_cdgo { get; set; }
        public Nullable<decimal> det_vles_hras { get; set; }
        public Nullable<decimal> det_vles_vlor_srvcio { get; set; }
        public string bloque { get; set; }
    }
}
