//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_vles_bck
    {
        public int id_vale { get; set; }
        public int enc_vles_nmro { get; set; }
        public string clntes_idntfccion { get; set; }
        public Nullable<System.DateTime> enc_vles_fcha { get; set; }
        public string enc_vles_hra_entrda { get; set; }
        public string enc_vles_hra_slda { get; set; }
        public Nullable<decimal> enc_vles_tmpo_dscnto { get; set; }
        public Nullable<decimal> enc_vles_tmpo_trbjdo { get; set; }
        public Nullable<decimal> enc_vles_vlor_trnsprtes { get; set; }
        public Nullable<decimal> enc_vles_vlor_almntos { get; set; }
        public Nullable<decimal> enc_vles_cmbstble { get; set; }
        public string enc_fac_nmro { get; set; }
        public string enc_vles_rlcion { get; set; }
        public string enc_vles_cncldo { get; set; }
        public Nullable<System.DateTime> enc_vles_qncna { get; set; }
        public string enc_vles_entrgdo { get; set; }
        public string enc_vles_obsrvcnes { get; set; }
        public string enc_vles_nmro_intrno { get; set; }
        public string enc_vles_fctrdo { get; set; }
        public string enc_vles_pgdo { get; set; }
        public string enc_vles_prcsdo { get; set; }
        public string enc_vles_prcsdo_fctra { get; set; }
        public string enc_vles_prcsdo_pgdo { get; set; }
        public string enc_vles_tmpral { get; set; }
        public string usrios_cdgo { get; set; }
        public Nullable<System.DateTime> fcha_prcso { get; set; }
    }
}
