//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lstas_prcio
    {
        public string cnvnios_cdgo { get; set; }
        public string srvcios_cdgo { get; set; }
        public Nullable<double> lstas_prcio_vlor { get; set; }
        public Nullable<double> lstas_prcio_iva { get; set; }
        public Nullable<int> lstas_prcio_prdo { get; set; }
        public string lstas_prcio_actvo { get; set; }
    }
}
