//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mnnto_vhclos
    {
        public string vhclos_idntfccion { get; set; }
        public string cncptos_mnnto_cdgo { get; set; }
        public Nullable<decimal> mnnto_nmro_hras { get; set; }
        public Nullable<decimal> mnnto_nmro_hras_trbjdas { get; set; }
        public Nullable<System.DateTime> mnnto_vhclos_fcha_incial { get; set; }
        public Nullable<System.DateTime> mnnto_vhclos_fcha_fnal { get; set; }
        public string mnnto_obsrvcnes { get; set; }
        public string mnnto_actvo { get; set; }
        public string usrios_cdgo { get; set; }
        public Nullable<System.DateTime> fcha_prcso { get; set; }
        public int consecutivo { get; set; }
    }
}
