//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvmnto_vhclos
    {
        public string vhclos_idntfccion { get; set; }
        public string cncptos_mvmnto_cdgo { get; set; }
        public Nullable<System.DateTime> mvmnto_vhclos_fcha { get; set; }
        public string mvmnto_vhclos_dcmnto { get; set; }
        public Nullable<decimal> mvmnto_vhclos_vlor { get; set; }
        public string mvmnto_vhclos_obsrvcnes { get; set; }
        public string usrios_cdgo { get; set; }
        public Nullable<System.DateTime> fcha_prcso { get; set; }
        public int consecutivo { get; set; }
    }
}
