//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prsnas
    {
        public string prsnas_idntfccion { get; set; }
        public string cddes_cdgo_expdcion { get; set; }
        public string prsnas_prmer_nmbre { get; set; }
        public string prsnas_sgndo_nmbre { get; set; }
        public string prsnas_prmer_aplldo { get; set; }
        public string prsnas_sgndo_aplldo { get; set; }
        public string prsnas_lgar_ncmnto { get; set; }
        public Nullable<System.DateTime> prsnas_fcha_ncmnto { get; set; }
        public string tpos_sngre_cdgo { get; set; }
        public string prsnas_actvo { get; set; }
        public string prsnas_nmbre_cmplto { get; set; }
        public string usrios_cdgo { get; set; }
        public Nullable<System.DateTime> fcha_prcso { get; set; }
    }
}
