//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrios
    {
        public string usrios_cdgo { get; set; }
        public string usrios_dscrpcion { get; set; }
        public string usrios_clve { get; set; }
        public string usrios_actvo { get; set; }
        public string usrios_admnstrdor { get; set; }
        public string usrios_frma_dgtal { get; set; }
        public string prfles_usrio_cdgo { get; set; }
    }
}
