//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrios_clves
    {
        public string usrios_cdgo { get; set; }
        public string usrios_clve { get; set; }
        public Nullable<System.DateTime> usrios_fcha_clve { get; set; }
        public Nullable<System.DateTime> usrios_fcha_prcso { get; set; }
    }
}
